TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += catflwr.db
DATA += catflwr.proto

#=======================================
include $(TOP)/configure/RULES
